### ISSUE TITLE
iOS 13 revealed `textField` on `UISearchBar`

### ISSUE THREAD

**Issue by olejnjak** [AckeeCZ/ACKategories#57]
So we can use it natively instead of our hack 🎉 

https://github.com/AckeeCZ/ACKategories/blob/1bc672b0c2b28fb635bb5a972e86f3615707c5de/ACKategories/UISearchBarExtensions.swift#L5

**Comment by janmisar** [comment]
But only for 13+ 😬 Removal is breaking change which is not good so I suggest just to deprecate this and we're done.

**Comment by olejnjak** [comment]
I think that the same approach as view use for `view.safeArea` is optimal, at least for now.

https://github.com/AckeeCZ/ACKategories/blob/1bc672b0c2b28fb635bb5a972e86f3615707c5de/ACKategories/UIView%2BSafeAreaCompat.swift#L22

**Comment by olejnjak** [comment]
Finally implemented in #61 in a bit different way as @LukasHromadnik suggested. The implementation is as discussed here, it uses `searchTextField` on iOS 13+, on older systems it uses the old  `value(forKey:)` method. 

In addition it is marked to be deprecated on iOS 13+, so it reports a deprecation warning if deployment target is iOS 13+ (we should do this also for the `UIView.safeArea`), otherwise it compiles without any warning.
